### ISSUE TITLE
uninitialized constant Rails

### ISSUE THREAD

**Issue by newstler** [appsignal/appsignal#54]
Hi,

Just integrated AppSignal gem as written in instruction and it breaks our deploy:

```
...
-----> Build finished
-----> Moving build to releases/7
$ mv "$build_path" "$release_path"
-----> Updating the current symlink
$ ln -nfs "$release_path" "current"
-----> Launching
$ cd "$release_path"
uninitialized constant Rails
(erb):3:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/erb.rb:863:in `eval'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/erb.rb:863:in `result'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/config.rb:77:in `load_config_from_disk'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/config.rb:30:in `initialize'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/cli.rb:44:in `new'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/cli.rb:44:in `config'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/cli.rb:123:in `validate_active_config'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/cli.rb:96:in `notify_of_deploy'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/lib/appsignal/cli.rb:25:in `run'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/gems/appsignal-0.11.12/bin/appsignal:7:in `<top (required)>'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/bin/appsignal:23:in `load'
/var/www/baby/releases/7/vendor/bundle/ruby/2.2.0/bin/appsignal:23:in `<main>'
! ERROR: Deploy failed.
-----> Cleaning up build
Deleting release
$ rm -rf "$release_path"
Unlinking current
$ ln -nfs "$previous_path" "current"
$ rm -f "deploy.lock"
OK
Connection to 52.18.217.157 closed.

!     Command failed.
      Failed with status 4864
```

We use gem `mina` instead of `capistrano`. `Rails 4.2.3`, `Ruby 2.2.1`. Had to remove integration while figure out why it breaks the deploy.

**Comment by matsimitsu** [comment]
Hi @newstler It seems it has something to do with the config file on disk. Could you send your appsignal.yml file to support@appsignal.com by any chance? I'd love to figure out what's happening here.

**Comment by newstler** [comment]
Done, thanx!
