### ISSUE TITLE
NoMethodError while sending queue: undefined method `each` for #<String>

### ISSUE THREAD

**Issue by MarkMurphy** [appsignal/appsignal#59]
```
I, [2015-08-07T17:13:24.289048 #27844]  INFO -- : Loading Rails (4.1.8) integration
I, [2015-08-07T17:13:25.168467 #27844]  INFO -- : Starting AppSignal 0.11.9 on 2.1.5/x86_64-linux
I, [2015-08-07T17:13:25.172209 #27844]  INFO -- : Loading Passenger integration
I, [2015-08-07T17:13:25.176199 #27844]  INFO -- : Loading Sidekiq integration
I, [2015-08-07T17:13:25.182180 #27844]  INFO -- : Started Appsignal agent
I, [2015-08-07T17:13:29.061251 #27957]  INFO -- : Forked worker process
E, [2015-08-07T17:14:02.158304 #27957] ERROR -- : NoMethodError while sending queue: undefined method `each' for #<String:0x00000009cb7da8>
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/middleware/delete_blanks.rb:6:in `call'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/middleware/chain.rb:81:in `block in invoke'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/middleware/chain.rb:84:in `call'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/middleware/chain.rb:84:in `invoke'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/post_processor.rb:13:in `block (2 levels) in post_processed_queue!'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/post_processor.rb:12:in `each'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/post_processor.rb:12:in `block in post_processed_queue!'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/post_processor.rb:11:in `map'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator/post_processor.rb:11:in `post_processed_queue!'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/aggregator.rb:42:in `post_processed_queue!'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/agent.rb:115:in `send_queue'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/agent.rb:42:in `block (2 levels) in start_thread'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/agent.rb:40:in `loop'
/var/www/app/shared/bundle/ruby/2.1.0/gems/appsignal-0.11.9/lib/appsignal/agent.rb:40:in `block in start_thread'
```

**Comment by thijsc** [comment]
Sorry for being slow in responding to this one, it fell through the cracks. This should be completely fixed in 1.0.
